=== rcole34/resources/schema/stateSchema.json
{
  "$id": "stateResources",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "educate": {
      "type": "array",
      "items": { "$ref": "#/definitions/resource" }
    },
    "advocate": {
      "type": "array",
      "items": { "$ref": "#/definitions/resource" }
    },
    "shop": {
      "type": "array",
      "items": { "$ref": "#/definitions/resource" }
    },
    "act": {
      "type": "array",
      "items": { "$ref": "#/definitions/resource" }
    }
  },
  "definitions": {
    "resource": {
      "title": "Resource",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "description": "The resource's id."
        },
        "type": {
          "type": "string",
          "description": "The resource's type",
          "enum": ["educate", "advocate", "act", "shop"]
        },
        "title": {
          "type": "string",
          "description": "The resource's title."
        },
        "subtitle": {
          "type": "string",
          "description": "The resource's subtitle."
        },
        "imageUrl": {
          "type": "string",
          "description": "The resource's image url."
        },
        "clickUrl": {
          "type": "string",
          "description": "The resource's click url."
        },
        "emailInfo": {
          "type": "object",
          "$ref": "#/definitions/emailInfo",
          "description": "The resource's email info."
        },
        "phoneNumber": {
          "type": "string",
          "description": "The resource's phone number."
        },
        "textInfo": {
          "type": "object",
          "$ref": "#/definitions/textInfo",
          "description": "The resource's text info."
        },
        "randomUrlList": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The resource's random url list."
        },
        "info": {
          "type": "string",
          "description": "The resource's info."
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The resource's tags."
        },
        "priority": {
          "type": "number",
          "description": "The resource's priority."
        }
      }
    },
    "emailInfo": {
      "title": "EmailInfo",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "recipients": {
          "type": "array",
          "items": { "type": "string" },
          "description": "The email's recipients."
        },
        "ccRecipients": {
          "type": "array",
          "items": { "type": "string" },
          "description": "The email's cc recipients."
        },
        "bccRecipients": {
          "type": "array",
          "items": { "type": "string" },
          "description": "The email's bcc recipients."
        },
        "subject": {
          "type": "string",
          "description": "The email's subject."
        },
        "messageBody": {
          "type": "string",
          "description": "The email's body."
        },
        "isHtml": {
          "type": "boolean",
          "description": "Whether or not html is used in the message body."
        }
      }
    },
    "textInfo": {
      "title": "TextInfo",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "recipients": {
          "type": "array",
          "items": { "type": "string" },
          "description": "The text's recipients."
        },
        "subject": {
          "type": "string",
          "description": "The text's subject."
        },
        "body": {
          "type": "string",
          "description": "The text's body."
        }
      }
    }
  }
}

=== rcole34/resources/states/california.json
{
  "advocate": [
    {
      "id": "19dc9e48-8de5-4544-8bbf-1ae34145b40d",
      "title": "Email CA Governor Gavin Newsom",
      "subtitle": "Make your voice heard by emailing those in power in government",
      "imageUrl": "https://www.pngitem.com/pimgs/m/22-227227_transparent-email-clipart-email-icon-transparent-background-hd.png",
      "emailInfo": {
        "recipients": [
          "governor@governor.ca.gov"
        ],
        "subject": "Condemn police brutality",
        "messageBody": "<p>Dear Governor Newsom,</p><p>My name is [Your Name] and I am constituent from [Your location]. I am contacting you because I want to know what you will do to protect black lives and prevent further instances of police brutality. I am calling to urge you to condemn police brutality, racial profiling, and the use of excessive force by police.</p><p>Sincerely,</p><p>[YOUR NAME]</p>",
        "isHtml": true
      },
      "tags": [
        "email",
        "CA",
        "California",
        "Local"
      ],
      "priority": 9
    }
  ],
  "educate": [],
  "shop": [],
  "act": [
    {
      "id": "84ecb46d-b843-4190-88f4-a7d8bb311cb8",
      "title": "BLM LA",
      "subtitle": "Get involved with a Black Lives Matter chapter in your state to join protests and take other actions to support the movement.",
      "imageUrl": "https://blacklivesmatter.com/wp-content/uploads/2020/04/blm-chapter-logo-la-250x243-01.png",
      "clickUrl": "http://blmla.org/",
      "tags": [
        "Local",
        "California",
        "BLM",
        "Help",
        "Protest",
        "Los Angeles",
        "Act"
      ],
      "priority": 10
    },
    {
      "id": "0a11b093-f103-45b2-8a9e-966343fe35d2",
      "title": "BLM Long Beach",
      "subtitle": "Get involved with a Black Lives Matter chapter in your state to join protests and take other actions to support the movement.",
      "imageUrl": "https://blacklivesmatter.com/wp-content/uploads/2020/04/blm-chapter-logo-long-beach-250x244-01.png",
      "clickUrl": "https://blmlbc.org/",
      "tags": [
        "Local",
        "California",
        "BLM",
        "Help",
        "Protest",
        "Long Beach",
        "Act"
      ],
      "priority": 10
    }
  ]
}

=== rcole34/resources/states/michigan.json
{
  "advocate": [],
  "educate": [],
  "shop": [],
  "act": [
    {
      "id": "e7f8c778-74b9-4754-a7df-e7acec1b1242",
      "type": "act",
      "title": "BLM Detroit",
      "subtitle": "Get involved with a Black Lives Matter chapter in your state to join protests and take other actions to support the movement.",
      "imageUrl": "https://blacklivesmatter.com/wp-content/uploads/2020/04/blm-chapter-logo-detroit-250x243-01.png",
      "clickUrl": "http://blmdetroit.com/",
      "tags": [
        "Local",
        "Michigan",
        "BLM",
        "Help",
        "Protest",
        "Detroit",
        "Act"
      ],
      "priority": 10
    },
    {
      "id": "a249e9fd-0070-4462-9f4b-690a121efd64",
      "type": "act",
      "title": "BLM Lansing",
      "subtitle": "Get involved with a Black Lives Matter chapter in your state to join protests and take other actions to support the movement.",
      "imageUrl": "https://blacklivesmatter.com/wp-content/uploads/2020/04/blm-chapter-logo-lansing-250x244-01.png",
      "clickUrl": "http://liberationpac.org/blmlansing",
      "tags": [
        "Local",
        "Michigan",
        "BLM",
        "Help",
        "Protest",
        "Lansing",
        "Act"
      ],
      "priority": 10
    },
    {
      "id": "b43666ac-dafe-4832-8230-a9a1190ced93",
      "type": "act",
      "title": "BLM Michigan",
      "subtitle": "Get involved with a Black Lives Matter chapter in your state to join protests and take other actions to support the movement.",
      "imageUrl": "https://blacklivesmatter.com/wp-content/uploads/2020/07/blm-chapter-logo-michigan-250x243-01.png",
      "clickUrl": "https://www.facebook.com/BLMMichigan/",
      "tags": [
        "Local",
        "Michigan",
        "BLM",
        "Help",
        "Protest",
        "Michigan",
        "Act"
      ],
      "priority": 10
    }
  ]
}

=== rcole34/resources/states/illinois.json
{
  "advocate": [],
  "educate": [],
  "shop": [],
  "act": [
    {
      "id": "e8ae9d57-4c31-4e9a-a5b6-5ff0c49eb3ab",
      "title": "BLM Chicago",
      "subtitle": "Get involved with a Black Lives Matter chapter in your state to join protests and take other actions to support the movement.",
      "imageUrl": "https://blacklivesmatter.com/wp-content/uploads/2020/04/blm-chapter-logo-chicago-250x244-01.png",
      "clickUrl": "http://blacklivesmatterchicago.com/",
      "tags": [
        "Local",
        "Illinois",
        "BLM",
        "Help",
        "Protest",
        "Chicago",
        "Act"
      ],
      "priority": 10
    }
  ]
}
